name: gio
description: A powerful http request library.
version: 0.2.0
homepage: https://github.com/arcticfox1919/gio

topics:
  - http

environment:
  sdk: ^3.4.0

dependencies:
  meta: ^1.16.0
  path: ^1.9.1
  http: ^1.5.0
  logging: ^1.3.0
  http_parser: ^4.1.2

dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.3
  gio_mock: ^0.1.0
  watcher: ^1.1.2
